apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- traefik-charts.yaml
- kubernetes-dashboard-charts.yaml
- dex-charts.yaml
- elastic-charts.yaml
- influxdata-charts.yaml
- loki-charts.yaml
- nextcloud-charts.yaml
- vernemq-charts.yaml
- prometheus-community-charts.yaml
- sonatype-charts.yaml
- twuni-charts.yaml
- authentik-charts.yaml
- blakeshome-charts.yaml
- coredns-charts.yaml
- deliveryhero-charts.yaml
- drone-charts.yaml
- falco-security-charts.yaml
- gitea-charts.yaml
- grafana-charts.yaml
- infracloudio-charts.yaml
- kasten-charts.yaml
- kubernetes-sigs-descheduler-charts.yaml
- nfs-subdir-external-provisioner-charts.yaml
- node-feature-discovery-charts.yaml
- stakater-charts.yaml
- weaveworks-kured-charts.yaml
