apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- metallb-system.yaml
- networking.yaml
- metrics.yaml
- kubernetes-dashboard.yaml
- monitoring.yaml
- storage.yaml
- registry.yaml
- system-upgrade.yaml
