---

# IP address of node
ansible_host: "192.168.10.112"
ansible_ssh_host: "{{ ansible_host }}"

# Ansible user to ssh into servers with
ansible_user: "ubuntu"
# ansible_ssh_pass: "ubuntu"
# ansible_ssh_common_args: "_o UserKnownHostsFile=/dev/null"
ansible_become_pass: "{{ k8s_master_b_sudo }}"
